---
title: "LOH bubble plot"
author: "Sehyun Oh"
date: "12/7/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE, results="hide", warning=FALSE}
suppressPackageStartupMessages({
    library(magrittr)
    library(GenomicRanges)
})
```


```{r}
out_dir = "~/data2/PureCN_manuscript/Revision"
loh_list = readRDS(file.path(out_dir, "luad_LOH_all.rds"))

names(loh_list) = stringr::str_extract(names(loh_list), "TCGA.{11}")
for (i in seq_along(loh_list)) {
    loh_list[[i]] = loh_list[[i]] %>% 
        tidyr::unite(sample_name, "C", "M", sep = "-") %>%
        makeGRangesListFromDataFrame(., keep.extra.columns = TRUE) %>%
        unlist
}
```

```{r}
# concordance ploidy calls (difference in ploidy estimate less than 0.5)
puri_ploi = read.csv("~/data2/PureCN_manuscript/Figures/Final_Tables/Table1_puri_ploi.csv")[,-1]
ploi_diff = abs(puri_ploi$Ploidy_ABS - puri_ploi$Ploidy_PCN_t) < 0.5
puri_ploi = puri_ploi[ploi_diff,]

# tumor purity greater than 30%
puri_30 = puri_ploi$Purity_PCN_t > 0.3
puri_ploi = puri_ploi[puri_30,]

# LUAD sampleID for downstream analysis 
luad_sampleId = puri_ploi[which(puri_ploi$Sample == "LUAD"),]$SampleId
loh_list = loh_list[luad_sampleId]
```


```{r}
loh_list[1:2]
```


```{r}

makeGRangesListFromDataFrame(loh_list[[i]],
                             keep.extra.columns = TRUE) %>% unlist


ind = which(colnames(loh_list[[1]]) == "sample_name")
loh_rate = as.data.frame(matrix(nrow = nrow(loh_list[[1]])))
loh_rate$gene.symbol = loh_list[[1]]$gene.symbol

for (i in seq_along(loh_list)) {
    names(loh_list[[i]])[ind] = names(loh_list[i])
    loh_rate = merge(loh_rate, loh_list[[i]], by = "gene.symbol", all = TRUE)
}

loh_rate = select(loh_rate, -c(V1))
loh_rate = data.frame(loh_rate[,-1], row.names = loh_rate[,1])
```


# Load ABSOLUTE GrangesList_hg38
```{r}
source("~/Documents/github/PureCN_manuscript/Figures/final/non_dup.R")
abs_gl = readRDS("~/Documents/github/subtypeHeterogeneity/inst/extdata/ABSOLUTE_grangeslist.rds")
luad_abs_gl = abs_gl[luad_442]   # 442 elements
```

