---
title: "Supplmentary Table 3. Benchmark"
author: "Sehyun Oh"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r, echo=FALSE, results="hide", warning=FALSE}
suppressPackageStartupMessages({
  library(patchwork)
  library(dplyr)
})
```

```{r}
library(patchwork)
library(dplyr)
```

```{r}
source("~/Documents/github/PureCN_manuscript/Figures/Final_Figures/non_dup.R")
```

```{r}
ov_dir = "~/Documents/github/PureCN_manuscript/Results"
luad_dir = "~/Documents/github/PureCN_manuscript/luad/Results"
```

## Load OV Benchmark output
```{r}
# PureCN algorithm
benchmark = readRDS(file.path(ov_dir, "benchmark/data/all_ovc_benchmark.rds"))
benchmark$SampleId = stringr::str_extract(benchmark$SampleId, "TCGA.{11}")

for (i in 2:10) {
  benchmark[, i] = as.numeric(benchmark[, i])
}

# SGZ algorithm
benchmark_SGZ = readRDS(file.path(ov_dir, "benchmark/data/all_ovc_benchmark_SGZ.rds"))
benchmark_SGZ$SampleId = stringr::str_extract(benchmark_SGZ$SampleId, "TCGA.{11}")

for (i in 2:8) {
  benchmark_SGZ[, i] = as.numeric(benchmark_SGZ[, i])
}
```

Mark the algorithm used
```{r}
benchmark$Algorithm = "PureCN"
benchmark_SGZ$Algorithm = "SGZ"
```

Subset the samples 
```{r}
benchmark_PCN = benchmark
rm(benchmark)

benchmark_PCN$Sample = "OV"
benchmark_SGZ$Sample = "OV"

benchmark_PCN = benchmark_PCN[which(benchmark_PCN$SampleId %in% ovc_236),]   # 277 --> 233
benchmark_SGZ = benchmark_SGZ[which(benchmark_SGZ$SampleId %in% ovc_236),]   # 274 --> 231
```

Two (2) absent OV_SGZ outputs
```{r}
benchmark_PCN[which(!benchmark_PCN$SampleId %in% benchmark_SGZ$SampleId),]$SampleId
```

## Load LUAD benchmark output
```{r}
# PureCN algorithm
benchmark_PCN_luad = readRDS(file.path(luad_dir, "benchmark/data/all_luad_benchmark.rds")) %>% subset(., select = -c(analyte))
benchmark_PCN_luad$SampleId = stringr::str_extract(benchmark_PCN_luad$SampleId, "TCGA.{11}")

for (i in 2:10) {
  benchmark_PCN_luad[, i] = as.numeric(benchmark_PCN_luad[, i])
}

# SGZ algorithm
benchmark_SGZ_luad = readRDS(file.path(luad_dir, "benchmark/data/all_luad_benchmark_SGZ.rds")) %>% subset(., select = -c(analyte))
benchmark_SGZ_luad$SampleId = stringr::str_extract(benchmark_SGZ_luad$SampleId, "TCGA.{11}")

for (i in 2:8) {
  benchmark_SGZ_luad[, i] = as.numeric(benchmark_SGZ_luad[, i])
}
```

Mark the algorithm used
```{r}
benchmark_PCN_luad$Algorithm = "PureCN"
benchmark_SGZ_luad$Algorithm = "SGZ"
```

Subset the samples
```{r}
benchmark_PCN_luad$Sample = "LUAD"
benchmark_SGZ_luad$Sample = "LUAD"

# SGZ failed to get the results from 2 samples
benchmark_PCN_luad = benchmark_PCN_luad[which(benchmark_PCN_luad$SampleId %in% luad_442),]   # 443 --> 441
benchmark_SGZ_luad = benchmark_SGZ_luad[which(benchmark_SGZ_luad$SampleId %in% luad_442),]   # 440 --> 438
```

One (1) absent LUAD_PCN + Four (4) absent LUAD_SGZ outputs
```{r}
luad_442[which(!luad_442 %in% benchmark_PCN_luad$SampleId)]
luad_442[which(!luad_442 %in% benchmark_SGZ_luad$SampleId)]
```

## Save the final tables
```{r}
benchmark_PCN_all = rbind(benchmark_PCN, benchmark_PCN_luad)
benchmark_SGZ_all = rbind(benchmark_SGZ, benchmark_SGZ_luad)
```

```{r}
out_dir = "~/Documents/github/PureCN_manuscript/Figures/Final_Tables"
write.csv(benchmark_PCN_all, file = file.path(out_dir, "Table3.1_benchmark_PCN.csv"))
write.csv(benchmark_SGZ_all, file = file.path(out_dir, "Table3.2_benchmark_SGZ.csv"))
```