---
title: "Table1 Sheet 1. Purity and Ploidy"
author: "Sehyun Oh"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r, echo=FALSE, results="hide", warning=FALSE}
suppressPackageStartupMessages({
  library(patchwork)
  library(dplyr)
})
```

```{r}
library(patchwork)
library(dplyr)
```

```{r}
source("~/wallabe4_backup/github/PureCN_manuscript/Figures/Final_Figures/non_dup.R")
```

```{r}
ov_dir = "~/wallabe4_backup/github/PureCN_manuscript/Results"
luad_dir = "~/wallabe4_backup/github/PureCN_manuscript/luad/Results"
```

## Combine TCGA-OV outputs
```{r}
ov_puri_ploi_t = readRDS(file.path(ov_dir,"purity_ploidy/data/ABS_w_tumor_only.rds"))
ov_puri_ploi_t = ov_puri_ploi_t[which(ov_puri_ploi_t$SampleId %in% ovc_236),] 
ov_puri_ploi_t = ov_puri_ploi_t[,c("SampleId", "Purity_ABS", "Ploidy_ABS", "Purity_tumor_only", "Ploidy_tumor_only")]
names(ov_puri_ploi_t)[4:5] = c("Purity_PCN_t", "Ploidy_PCN_t")

ov_puri_ploi_p = readRDS(file.path(ov_dir,"purity_ploidy/data/ABS_w_matching_normal.rds"))
ov_puri_ploi_p = ov_puri_ploi_p[which(ov_puri_ploi_p$SampleId %in% ovc_236),] 
ov_puri_ploi_p = ov_puri_ploi_p[,c("SampleId", "Purity_matching_normal", "Ploidy_matching_normal")]
names(ov_puri_ploi_p)[2:3] = c("Purity_PCN_p", "Ploidy_PCN_p")
```

```{r}
ov_FACETS = read.csv("~/Documents/github/FACETS/OVC/Results/purity_ploidy/ABS_PureCN_FACETS.csv")[,-1]
ov_FACETS = ov_FACETS[ov_FACETS$SampleId.x %in% ovc_236,]
ov_FACETS = ov_FACETS[,c("SampleId.x", "Purity_FACETS", "Ploidy_FACETS")]
names(ov_FACETS)[1] = "SampleId"
```

```{r message=FALSE, warning=FALSE}
ov_puri_ploi_all = left_join(ov_puri_ploi_t, ov_puri_ploi_p, by = "SampleId") %>% left_join(., ov_FACETS, by = "SampleId")
# ov_puri_ploi_all[,c(2:9)] = round(ov_puri_ploi_all[,c(2:9)], digits = 2)
ov_puri_ploi_all$Sample = "OV"
```

```{r}
head(ov_puri_ploi_all, 3)
```

## Combine TCGA-LUAD outputs
```{r}
luad_puri_ploi_t = readRDS(file.path(luad_dir, "purity_ploidy/data/luad_ABS_w_tumor_only.rds"))
luad_puri_ploi_t = luad_puri_ploi_t[which(luad_puri_ploi_t$SampleId %in% luad_442),]
luad_puri_ploi_t = luad_puri_ploi_t[,c("SampleId", "Purity_ABS", "Ploidy_ABS", "Purity_tumor_only", "Ploidy_tumor_only")]
names(luad_puri_ploi_t)[4:5] = c("Purity_PCN_t", "Ploidy_PCN_t")

luad_puri_ploi_p = readRDS(file.path(luad_dir, "purity_ploidy/data/luad_ABS_w_matching_normal.rds"))
luad_puri_ploi_p = luad_puri_ploi_p[which(luad_puri_ploi_p$SampleId %in% luad_442),]
luad_puri_ploi_p = luad_puri_ploi_p[,c("SampleId", "Purity_matching_normal", "Ploidy_matching_normal")]
names(luad_puri_ploi_p)[2:3] = c("Purity_PCN_p", "Ploidy_PCN_p")
```

```{r}
luad_FACETS = read.csv("~/Documents/github/FACETS/LUAD/Results/purity_ploidy/luad_ABS_PureCN_FACETS.csv")[,-1]
luad_FACETS = luad_FACETS[luad_FACETS$SampleId.x %in% luad_442,]
luad_FACETS = luad_FACETS[,c("SampleId.x", "Purity_FACETS", "Ploidy_FACETS")]
names(luad_FACETS)[1] = "SampleId"
```

```{r message=FALSE, warning=FALSE}
luad_puri_ploi_all = left_join(luad_puri_ploi_t, luad_puri_ploi_p, by = "SampleId") %>% left_join(., luad_FACETS, by = "SampleId")
# luad_puri_ploi_all[,c(2:9)] = round(luad_puri_ploi_all[,c(2:9)], digits = 2)
luad_puri_ploi_all$Sample = "LUAD"
```

```{r}
head(luad_puri_ploi_all, 3)
```

## Combine all the outputs: TCGA-OV and TCGA-LUAD
```{r}
puri_ploi_all = rbind(ov_puri_ploi_all, luad_puri_ploi_all)
```

```{r}
dim(puri_ploi_all)
head(puri_ploi_all, 3)
tail(puri_ploi_all, 3)
```

##### Save
Table1.Sheet1. Purity and Ploidy
```{r eval=FALSE}
write.csv(puri_ploi_all, file = "~/wallabe4_backup/github/PureCN_manuscript/Figures/Final_Tables/Table1_puri_ploi.csv")
```