---
title: "TCGA-LUAD: TMB comparison to Lawrence paper"
author: "Sehyun Oh"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE, results="hide", warning=FALSE}
suppressPackageStartupMessages({
  library(stringr)
  library(ggplot2)
  library(cowplot)
})
```

```{r echo=FALSE, message=FALSE}
library(stringr)
library(ggplot2)
library(cowplot)
```

## Load TMB from Lawrence paper
```{r}
lawrence_tmb = read.csv("~/Documents/github/PureCN_Pipeline/analysis/mutation_burden/nature12213-s2 - Table S2.csv")
table(lawrence_tmb$datatype)
```

### Subset lung adenocarcinoma output
```{r}
luad_tmb = lawrence_tmb[lawrence_tmb$tumor_type == "Lung adenocarcinoma",]
luad_tmb = luad_tmb[which(luad_tmb$datatype == "exome"),]
luad_tmb$name[1:20]

luad_tmb$SampleId = gsub("LUAD", "TCGA", luad_tmb$name)
luad_tmb$SampleId = str_extract(luad_tmb$SampleId, "TCGA.{8}")
```

## Load TMB from PureCN
```{r message=FALSE}
TMB_dir = "~/Documents/github/PureCN_manuscript/luad/Results/TMB"
out_dir = file.path(TMB_dir, "extdata")

luad_tmb_purecn = read.table(file.path(out_dir, "931070_TMB.tsv"))
colnames(luad_tmb_purecn)[1] = "barcode"
luad_tmb_purecn$SampleId = str_extract(luad_tmb_purecn$barcode, "TCGA.{8}")
```

## Combine TMB from PureCN and Lawrence paper
```{r}
luad_tmb$TMB_lawrence = luad_tmb$coding_mutation_rate * 1e+6 
luad_tmb_sub = luad_tmb[, c("SampleId", "TMB_lawrence")]
luad_tmb_all = dplyr::left_join(luad_tmb_purecn, luad_tmb_sub, by = "SampleId")
```

## Plot PureCN tumor_only against Lawrence paper result
```{r message=FALSE, fig.width = 5, fig.height = 4.5}
cor = round(cor(luad_tmb_all$TMB_tumor, luad_tmb_all$TMB_lawrence, use = "complete.obs"), 2)

tmb_plot = ggplot(luad_tmb_all) +
  geom_point(aes(x = TMB_lawrence, 
                 y = TMB_tumor),
             col = "red",
             alpha = 1/3) + 
  labs(x = "from Lawrence Paper", 
       y = "from PureCN (tumor-only)", 
       title = "TCGA-LUAD: TMB Comparison") +
  # styling
  geom_abline(col = "grey", lwd = 0.5) + 
  theme_light() +
  theme(plot.title = element_text(size = 14, face = "bold", 
                                  margin = margin(10, 0, 10, 0)),
        axis.text.x = element_text(size = 10, face = "bold"), 
        axis.text.y = element_text(size = 10, face = "bold"), 
        axis.title.x = element_text(size = 12, face = "bold"), 
        axis.title.y = element_text(size = 12, face = "bold"), 
        axis.line = element_line(colour = "black", size = 0.5),
        panel.grid.major = element_line(), 
        panel.grid.minor = element_line(),
        legend.title = element_text(size=12, face="bold"),
        legend.text = element_text(size = 10, face = "bold"),
        plot.margin = unit(c(0.5, 2.6, 0.2, 1), "cm")) +
  scale_x_continuous(limits = c(0, 125), breaks = seq(0,125,25)) +
  scale_y_continuous(limits = c(0, 125), breaks = seq(0,125,25))

ggdraw(add_sub(tmb_plot, paste("Concordance\ncorrelation =", cor),
               vpadding = grid::unit(0, "lines"),
               y = 11.5, x = 0.05,
               hjust = 0,
               fontface = "italic",
               size = 12))
```

## Plot PureCN matching_normal against Lawrence paper result
```{r message=FALSE, fig.width = 5, fig.height = 4.5}
cor = round(cor(luad_tmb_all$TMB_paired, luad_tmb_all$TMB_lawrence, use = "complete.obs"), 2)

tmb_plot = ggplot(luad_tmb_all) +
  geom_point(aes(x = TMB_lawrence, 
                 y = TMB_paired),
             col = "red",
             alpha = 1/3) + 
  labs(x = "from Lawrence Paper", 
       y = "from PureCN (paired)", 
       title = "TCGA-LUAD: TMB Comparison") +
  # styling
  geom_abline(col = "grey", lwd = 0.5) + 
  theme_light() +
  theme(plot.title = element_text(size = 14, face = "bold", 
                                  margin = margin(10, 0, 10, 0)),
        axis.text.x = element_text(size = 10, face = "bold"), 
        axis.text.y = element_text(size = 10, face = "bold"), 
        axis.title.x = element_text(size = 12, face = "bold"), 
        axis.title.y = element_text(size = 12, face = "bold"), 
        axis.line = element_line(colour = "black", size = 0.5),
        panel.grid.major = element_line(), 
        panel.grid.minor = element_line(),
        legend.title = element_text(size=12, face="bold"),
        legend.text = element_text(size = 10, face = "bold"),
        plot.margin = unit(c(0.5, 2.6, 0.2, 1), "cm")) +
  scale_x_continuous(limits = c(0, 125), breaks = seq(0,125,25)) +
  scale_y_continuous(limits = c(0, 125), breaks = seq(0,125,25))

ggdraw(add_sub(tmb_plot, paste("Concordance\ncorrelation =", cor),
               vpadding = grid::unit(0, "lines"),
               y = 11.5, x = 0.05,
               hjust = 0,
               fontface = "italic",
               size = 12))
```