---
title: "dNdSCV outputs from tumor-only and matching-normal samples"
author: "Sehyun Oh"
date: "`r Sys.Date()`"
output:
  BiocStyle::html_document:
    toc: true
    toc_float: true
    toc_depth: 4
vignette: >
  % \VignetteIndexEntry{Statistical analysis output}
  % \VignetteEngine{knitr::rmarkdown}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE, eval=FALSE)
```



# Check KRAS 
Extract KRAS status
```{r eval=FALSE}
i = 1
runtype = c("tumor_only", "matching_normal")[i]
data_dir = file.path("/nobackup/16tb_a/CNVworkflow_LUAD/purecn_output/PureCN", runtype)

sample_dir = list.files(data_dir)
file_list = sapply(sample_dir, function(x) list.files(file.path(data_dir, x)))
mut = sapply(file_list, function(x) x[grep("*_variants.csv$", x)])
source("~/Documents/github/PureCN_manuscript/Figures/Final_Figures/non_dup.R")
sub_ind = which(stringr::str_extract(names(mut), "TCGA.{11}") %in% luad_442)
mut = mut[sub_ind]

p = read.csv(file.path(data_dir, names(mut[i]), mut[[i]]))
colNames = colnames(p)
test = as.data.frame(matrix(NA, ncol = length(colNames)))
colnames(test) = colNames

for (i in seq_along(mut)) {
    p = read.csv(file.path(data_dir, names(mut[i]), mut[[i]]))
    q = p[which(p$gene.symbol == "KRAS"),]
    test = rbind(test, q)
}

# write.csv(test, paste0("~/data2/PureCN_manuscript/Revision/dNdSCV/data/KRAS_",runtype,".csv"))
```

```{r eval=FALSE}
out_dir = "~/data2/PureCN_manuscript/Revision/dNdSCV"
kras_t = read.csv(file.path(out_dir, "data/KRAS_tumor_only.csv"))[-1,-1]
kras_m = read.csv(file.path(out_dir, "data/KRAS_matching_normal.csv"))[-1,-1]
```




# Filter with ML.SOMATIC
**Significant genes in tumor-only**   
Because I didn't used COSMIC VCF fils (COSMIC.CNT) for PureCN run, many SNVs in dbSNP 
are removed in the prior.somatic filtering process. We decided to do 'quick and dirty' 
fix of it, by adding COSMIC SNVs with CNT >= 20


```{r}
# FDR filtering
runtype = "tumor_only"
dnds_out_dir = file.path("/nobackup/16tb_b/CNVworkflow_revision/dNdSCV/outputs/LUAD", runtype)
t_all = readRDS(file.path(dnds_out_dir, paste0("dndsout_LUAD_", runtype, "_rescalePriors.rds")))
runtype = "matching_normal"
dnds_out_dir = file.path("/nobackup/16tb_b/CNVworkflow_revision/dNdSCV/outputs/LUAD", runtype)
m_all = readRDS(file.path(dnds_out_dir,"ML_SOMATIC_FILTER", paste0("dndsout_LUAD_", runtype, ".rds")))

t = t_all$sel_cv[,c("gene_name", "qglobal_cv")]
m = m_all$sel_cv[,c("gene_name", "qglobal_cv")]
```

```{r}
# signif_dir = "/nobackup/16tb_b/CNVworkflow_revision/dNdSCV/outputs/LUAD"
# t = read.csv(file.path(signif_dir, "tumor_only/signif_genes_LUAD_tumor_only_rescalePriors.csv"))[,-1]
# m = read.csv(file.path(signif_dir, "matching_normal/ML_SOMATIC_FILTER/signif_genes_LUAD_matching_normal.csv"))[,-1]

colnames(t)[2] = "qglobal_cv_tumorOnly"
colnames(m)[2] = "qglobal_cv_matchingN"

all = merge(t, m, by = "gene_name")
write.csv(all, "~/data2/PureCN_manuscript/Revision/dNdSCV/data/qgloba_cv_all.csv")
```

### Summary Table
```{r message=FALSE}
# summary = dplyr::full_join(t, m)
# colnames(summary) = c("Gene", "Tumor only", "Matching normal")
# summary

sub = all[which(all$qglobal_cv_tumorOnly < 0.01 | all$qglobal_cv_matchingN < 0.01),]
colnames(sub) = c("Gene", "Tumor only", "Matching normal")
sub
```

```{r echo=FALSE, eval=FALSE}
sub = sub[,c("Gene", "Matching normal", "Tumor only")]
sub = sub[order(sub$`Matching normal`),]
write.csv(sub, file = "~/data2/PureCN_manuscript/Revision/dNdSCV/data/SignificantGenes.csv")
```

```{r}
FDRcutoff = 0.01
t_sig = t[which(t$qglobal_cv_tumorOnly < FDRcutoff),]
m_sig = m[which(t$qglobal_cv_tumorOnly < FDRcutoff),]
dplyr::inner_join(t_sig, m_sig, by = "gene_name")
all_sig = merge(t_sig, m_sig, by = "gene_name")
```

### Venn Diagram
```{r fig.width=4.5, fig.height=4.5}
library(VennDiagram)

grid.newpage()
draw.pairwise.venn(area1 = nrow(m_sig),
                   area2 = nrow(t_sig),
                   cross.area = nrow(all_sig),
                   category = c("matching_normal", "tumor_only"),
                   lty = rep("blank", 2), 
                   fill = c("light blue", "pink"), 
                   alpha = rep(0.5, 2), 
                   cat.pos = c(0, 0), 
                   cat.dist = rep(0.025, 2))
```

### Cancer Genes
```{r fig.height=4.5, fig.width=4.5}
plot(x = -log(all_sig$qglobal_cv_matchingN), 
     y = -log(all_sig$qglobal_cv_tumorOnly),
     main = "Cancer Genes in LUAD (-log(q-value))",
     xlab = "Matching-normal",
     ylab = "Tumor-only",
     xlim = c(0,20), ylim = c(0,20))
abline(0, 1, col = "red")
```

