---
title: "TMB: TCGA-OV and TCGA-LUAD"
author: "Sehyun Oh"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE, results="hide", warning=FALSE}
suppressPackageStartupMessages({
  library(stringr)
  library(ggplot2)
  library(cowplot)
  library(scales)
})
```

```{r}
library(stringr)
library(ggplot2)
library(cowplot)
library(scales)
```

```{r echo=FALSE}
# figure styling --> customPlot
source("~/wallabe4_backup/github/PureCN_manuscript_backup/Figures/manuscript_figure_style.R")

# non-duplicated samples list
source("~/wallabe4_backup/github/PureCN_manuscript_backup/Figures/Final_Figures/non_dup.R")
```

```{r TMB_OV}
TMB_dir = "~/wallabe4_backup/github/PureCN_manuscript_backup/Results/TMB"
out_dir = file.path(TMB_dir, "extdata")

TMB_931070 = read.table(file.path(out_dir, "931070_TMB.tsv"))
TMB_S0293689 = read.table(file.path(out_dir, "S0293689_TMB.tsv"))
TMB_purecn = rbind(TMB_931070, TMB_S0293689)

TMB_purecn = TMB_purecn[which(stringr::str_extract(TMB_purecn$sampleID, "TCGA.{11}") %in% ovc_236),]
TMB_OV = TMB_purecn
rm(TMB_purecn)
```

```{r TMB_OV_dup, echo=FALSE, eval=FALSE}
dup = intersect(TMB_931070$sampleID, TMB_S0293689$sampleID)
dup_subset = TMB_purecn[which(TMB_purecn$sampleID %in% dup),]
dup_subset = dup_subset %>%
  dplyr::group_by(sampleID) %>%
  dplyr::summarise(TMB_tumor = mean(TMB_tumor), 
                   TMB_paired = mean(TMB_paired)) %>%
  as.data.frame(.)

TMB_purecn = TMB_purecn[-which(TMB_purecn$sampleID %in% dup),]
TMB_purecn = rbind(TMB_purecn, dup_subset) 
```

```{r TMB_LUAD}
TMB_dir = "~/wallabe4_backup/github/PureCN_manuscript_backup/luad/Results/TMB"
out_dir = file.path(TMB_dir, "extdata")

TMB_purecn = read.table(file.path(out_dir, "931070_TMB.tsv"))
TMB_purecn = TMB_purecn[which(stringr::str_extract(TMB_purecn$sampleID, "TCGA.{11}") %in% luad_442),]

TMB_LUAD = TMB_purecn
rm(TMB_purecn)
```

```{r}
TMB_OV$Sample = "OV"
TMB_LUAD$Sample = "LUAD"
TMB_purecn = rbind(TMB_LUAD, TMB_OV)
```

```{r echo=FALSE, fig.width = 5, fig.height = 4.2, eval=FALSE}
purecn_puri = ggplot(TMB_purecn) +
  geom_point(aes(x = TMB_tumor, y = TMB_paired, colour = Sample),
             alpha = 1/3) + 
  scale_color_manual(values=c("navy", "red")) +
  labs(x = "Tumor only", 
       y = "Tumor paired", 
       title = "Tumor mutation burden (TMB)") +
  customPlot +
  scale_x_continuous(limits = c(0, 125), breaks = seq(0,125,25)) +
  scale_y_continuous(limits = c(0, 125), breaks = seq(0,125,25))

purecn_puri
```

```{r fig.width = 4.2, fig.height = 4.5}
cor = round(cor(TMB_purecn$TMB_tumor, 
                TMB_purecn$TMB_paired, 
                use = "complete.obs"), 2)

purecn_puri = ggplot(TMB_purecn) +
  geom_point(aes(x = TMB_tumor, y = TMB_paired, colour = Sample),
             alpha = 1/3) + 
  scale_color_manual(values=c("navy", "red")) +
  labs(x = "Tumor only", 
       y = "Tumor paired", 
       title = "A. Tumor mutation burden (TMB)") +
  geom_abline(col = "grey", lwd = 0.5) + 
  customPlot +
  theme(legend.position = c(0.8, 0.12),
        legend.title = element_blank(),
        legend.text = element_text(size = 12, face = "plain"),
        legend.background = element_rect(fill = NA)) +
  scale_x_continuous(trans=log2_trans(), breaks=trans_breaks("log2", function(x) 2^x)) +
  scale_y_continuous(trans=log2_trans(), breaks=trans_breaks("log2", function(x) 2^x))
  # scale_x_log10() + scale_y_log10()

purecn_puri = ggdraw(add_sub(purecn_puri, paste("Concordance\ncorrelation =", cor), 
               vpadding = grid::unit(0, "lines"), 
               y = 11, x = 0.05, 
               hjust = 0, 
               fontface = "italic", 
               size = 12))

purecn_puri
```

```{r eval=FALSE}
out_dir = "~/wallabe4_backup/github/PureCN_manuscript_backup/Figures/final"
saveRDS(purecn_puri, file = file.path(out_dir, "Fig3A.TMB.rds"))
```