---
title: "BenchmarkTumorOnly Plots"
author: "Sehyun Oh"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r, echo=FALSE, results="hide", warning=FALSE}
suppressPackageStartupMessages({
  library(dplyr)
  library(cowplot)
  library(stringr)
  library(ggplot2)
})
```

```{r}
library(dplyr)
library(cowplot)
library(stringr)
library(ggplot2)
```

## Load benchmark output
```{r}
results_dir = "~/wallabe4_backup/github/PureCN_manuscript_backup/Results"
benchmark = readRDS(file.path(results_dir, "benchmark/data/all_ovc_benchmark.rds"))
```

```{r}
head(benchmark)
```

```{r echo=FALSE}
for (i in 2:10) {
  benchmark[, i] = as.numeric(benchmark[, i])
}
```

```{r echo=FALSE}
# figure styling --> customPlot
source("~/wallabe4_backup/github/PureCN_manuscript_backup/Figures/manuscript_figure_style.R")
source("~/wallabe4_backup/github/PureCN_manuscript_backup/Figures/Final_Figures/non_dup.R")
```

```{r}
benchmark = benchmark[str_extract(benchmark$SampleId,"TCGA.{11}") %in% ovc_236,] 
```

## Plot AUC gain
Calculate the difference
```{r}
benchmark$diff = benchmark$AUC.POSTERIOR.SOMATIC - benchmark$AUC.AR
```

```{r message=FALSE, echo=FALSE}
benchmark_plot = ggplot(benchmark,
                        aes(x = Purity,
                            y = diff)) +
  geom_point(alpha = 1/3) + 
  scale_color_gradient(low = "blue", high = "red") + 
  labs(x = "Purity",
       y = "AUC gain PreCN over allelic fraction",   # AUC.POSTERIOR.SOMATIC - AUC.AR
       title = "A. TCGA-OV: AUC gain") + 
  xlim(0, 1) + ylim(0, 0.5) +
  geom_hline(yintercept = 0, linetype = "solid", color = "grey") +
  theme_light() +
  customPlot +
  scale_x_continuous(limits=c(0, 1), breaks=seq(0,1,0.2)) +
  scale_y_continuous(limits=c(-0.2, 0.4), breaks=seq(-0.2,0.4,0.1)) +
  # geom_smooth(method = lm, formula = y ~ splines::bs(x, 3), se = FALSE) +
  geom_smooth(colour = "red", size = 0.5)
```

```{r fig.width = 4.5, fig.height = 4.5}
benchmark_plot

# out_dir = "~/wallabe4_backup/github/PureCN_manuscript_backup/Figures/Final_Figures"
# saveRDS(benchmark_plot, file = file.path(out_dir, "Fig2A.ovc_AUC_gain.rds"))
```

## Plot SNV calling accuracy 
```{r}
accuracy.somatic = data.frame(accuracy = benchmark$Accuracy.Somatic, SNV = "Somatic")
accuracy.germline = data.frame(accuracy = benchmark$Accuracy.Germline, SNV = "Germline")
accuracy_all = rbind(accuracy.somatic, accuracy.germline)

summary(accuracy.somatic[,1])
summary(accuracy.germline[,1])
```

```{r}
ov_accuracy = ggplot(accuracy_all, aes(x = accuracy, fill = SNV)) +
  geom_histogram(binwidth=0.02, alpha=0.4, position = "identity") + 
  labs(x = "Accuracy",
       y = "Count",
       title = "E. TCGA-OV: Accuracy") + 
  scale_fill_manual(values = c("red", "black")) +
  theme_light() +
  theme(plot.title = element_text(size = 14, 
                                  face = "bold", 
                                  margin = margin(10, 0, 10, 0)),
        axis.text.x = element_text(size = 10, face = "bold"), 
        axis.text.y = element_text(size = 10, face = "bold"), 
        axis.title.x = element_text(size = 12, face = "bold"), 
        axis.title.y = element_text(size = 12, face = "bold"), 
        axis.line = element_line(colour = "black", size = 0.5),
        panel.grid.major = element_line(), 
        panel.grid.minor = element_line(),
        legend.title = element_blank(),
        legend.background = element_rect(fill = NA),
        # legend.title = element_text(size=12, face="bold"),
        legend.text = element_text(size = 10, face = "bold"),
        plot.margin = unit(c(0.5, 0.5, 0.2, 0.5), "cm")) +
  theme(legend.position = c(0.2, 0.87)) +
  coord_cartesian(xlim = c(0.3, 1), ylim = c(0, 70)) +
  scale_x_continuous(breaks = seq(0.3, 1, 0.1)) + 
  scale_y_continuous(breaks = seq(0, 70, 10))
```

```{r fig.width = 4, fig.height = 4.5}
ov_accuracy

# out_dir = "~/wallabe4_backup/github/PureCN_manuscript_backup/Figures/Final_Figures"
# saveRDS(ov_accuracy, file = file.path(out_dir, "Fig2E.ov_accuracy.rds"))
```

## Plot SNV calling accuracy using SGZ algorithm
```{r echo=FALSE}
results_dir = "~/wallabe4_backup/github/PureCN_manuscript_backup/Results"
benchmark_SGZ = readRDS(file.path(results_dir, "benchmark/data/all_ovc_benchmark_SGZ.rds"))

for (i in 2:8) {
  benchmark_SGZ[, i] = as.numeric(benchmark_SGZ[, i])
}
```

```{r}
benchmark_SGZ = benchmark_SGZ[str_extract(benchmark_SGZ$SampleId,"TCGA.{11}") %in% ovc_236,]   # 231 obs. 
```

```{r echo=FALSE}
accuracy.somatic = data.frame(accuracy = benchmark_SGZ$Accuracy.Somatic, SNV = "Somatic")
accuracy.germline = data.frame(accuracy = benchmark_SGZ$Accuracy.Germline, SNV = "Germline")
accuracy_all = rbind(accuracy.somatic, accuracy.germline)
```

```{r}
summary(accuracy.somatic[,1])
summary(accuracy.germline[,1])
```

```{r}
accuracy.somatic = data.frame(accuracy = benchmark_SGZ$Accuracy.Somatic, SNV = "Somatic")
accuracy.germline = data.frame(accuracy = benchmark_SGZ$Accuracy.Germline, SNV = "Germline")
accuracy_all = rbind(accuracy.somatic, accuracy.germline)

summary(accuracy.somatic[,1])
summary(accuracy.germline[,1])
```

```{r}
ov_sgz_accuracy = ggplot(accuracy_all, aes(x = accuracy, fill = SNV)) +
  geom_histogram(binwidth=0.02, alpha=0.4, position = "identity") + 
  labs(x = "Accuracy",
       y = "Count",
       title = "G. TCGA-OV: Accuracy (SGZ)") + 
  scale_fill_manual(values = c("red", "black")) +
  theme_light() +
  theme(plot.title = element_text(size = 14, 
                                  face = "bold", 
                                  margin = margin(10, 0, 10, 0)),
        axis.text.x = element_text(size = 10, face = "bold"), 
        axis.text.y = element_text(size = 10, face = "bold"), 
        axis.title.x = element_text(size = 12, face = "bold"), 
        axis.title.y = element_text(size = 12, face = "bold"), 
        axis.line = element_line(colour = "black", size = 0.5),
        panel.grid.major = element_line(), 
        panel.grid.minor = element_line(),
        legend.title = element_blank(),
        # legend.title = element_text(size=12, face="bold"),
        legend.text = element_text(size = 10, face = "bold"),
        plot.margin = unit(c(0.5, 0.5, 0.2, 0.5), "cm")) +
  theme(legend.position = c(0.2, 0.87)) +
  coord_cartesian(xlim = c(0.3, 1), ylim = c(0, 70)) +
  scale_x_continuous(breaks = seq(0.3, 1, 0.1)) + 
  scale_y_continuous(breaks = seq(0, 70, 10))
```

```{r fig.width = 4, fig.height = 4.5}
ov_sgz_accuracy

# out_dir = "~/wallabe4_backup/github/PureCN_manuscript_backup/Figures/Final_Figures"
# saveRDS(ov_sgz_accuracy, file = file.path(out_dir, "Fig2G.ov_sgz_accuracy.rds"))
# saveRDS(ov_sgz_accuracy, file = file.path(out_dir, "Fig2F.ov_sgz_accuracy.rds"))
```

```{r}
sessionInfo()
```