---
title: "PureCN TMB: tumor-only vs. paired"
author: "Sehyun Oh"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo=FALSE, results="hide", warning=FALSE}
suppressPackageStartupMessages({
  library(stringr)
  library(ggplot2)
  library(cowplot)
})
```

```{r}
library(stringr)
library(ggplot2)
library(cowplot)
```

## Load TMB from PureCN
```{r message=FALSE}
TMB_dir = "~/Documents/github/PureCN_manuscript/Results/TMB"
out_dir = file.path(TMB_dir, "extdata")

TMB_931070 = read.table(file.path(out_dir, "931070_TMB.tsv"))
TMB_S0293689 = read.table(file.path(out_dir, "S0293689_TMB.tsv"))
TMB_purecn = rbind(TMB_931070, TMB_S0293689)
```

## Merge duplicates
Out of 307 results from both kits, 50 are processed by both kits (25 from each kits)

##### Subset duplicates
```{r}
dup = intersect(TMB_931070$sampleID, TMB_S0293689$sampleID)
dup
```

```{r}
dup_subset = TMB_purecn[which(TMB_purecn$sampleID %in% dup),]
```

##### Average out duplicates
```{r}
dup_subset = dup_subset %>%
  dplyr::group_by(sampleID) %>%
  dplyr::summarise(TMB_tumor = mean(TMB_tumor), 
                   TMB_paired = mean(TMB_paired)) %>%
  as.data.frame(.)
```

```{r}
TMB_purecn = TMB_purecn[-which(TMB_purecn$sampleID %in% dup),]
TMB_purecn = rbind(TMB_purecn, dup_subset) 
```

## Compare PureCN outputs: with or wihtout matching-normal 
Results from 282 samples are plotted

```{r echo=FALSE, fig.width = 5, fig.height = 4.5}
cor = round(cor(TMB_purecn$TMB_tumor, TMB_purecn$TMB_paired, use = "complete.obs"), 2)

purecn_puri = ggplot(TMB_purecn) +
  geom_point(aes(x = TMB_tumor, 
                 y = TMB_paired),
             col = "red",
             alpha = 1/3) + 
  labs(x = "Tumor only", 
       y = "Tumor paired", 
       title = "TMB from TCGA-OV") +
  # styling
  geom_abline(col = "grey", lwd = 0.5) + 
  theme_light() +
  theme(plot.title = element_text(size = 14, face = "bold", 
                                  margin = margin(10, 0, 10, 0)),
        axis.text.x = element_text(size = 10, face = "bold"), 
        axis.text.y = element_text(size = 10, face = "bold"), 
        axis.title.x = element_text(size = 12, face = "bold"), 
        axis.title.y = element_text(size = 12, face = "bold"), 
        axis.line = element_line(colour = "black", size = 0.5),
        panel.grid.major = element_line(), 
        panel.grid.minor = element_line(),
        legend.title = element_text(size=12, face="bold"),
        legend.text = element_text(size = 10, face = "bold"),
        plot.margin = unit(c(0.5, 2.6, 0.2, 1), "cm")) +
  scale_x_continuous(limits = c(0, 35), breaks = seq(0,35,5)) +
  scale_y_continuous(limits = c(0, 35), breaks = seq(0,35,5))

ggdraw(add_sub(purecn_puri, paste("Concordance\ncorrelation =", cor),
               vpadding = grid::unit(0, "lines"),
               y = 11.5, x = 0.05,
               hjust = 0,
               fontface = "italic",
               size = 12))
```
