---
title: "LOH Plots (Tumor-only)"
author: "Sehyun Oh"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r, echo=FALSE, results="hide", warning=FALSE}
suppressPackageStartupMessages({
  library(dplyr)
  library(cowplot)
})
```

```{r}
library(dplyr)
library(cowplot)
```

## Load LOH output
```{r}
results_dir = "~/wallabe4_backup/github/PureCN_manuscript/Results/LOH"
TP53_all = read.csv(file.path(results_dir, "extdata/OV_TP53_all.tsv"))[,-1]
HLA_all = read.csv(file.path(results_dir, "extdata/OV_HLA_all.tsv"))[,-1]
```

## TP53
Total 223 obs.
```{r}
both = which(TP53_all$TP53_LOH == TRUE & TP53_all$TP53_LOH_t == TRUE)   # 222
neither = which(TP53_all$TP53_LOH == FALSE & TP53_all$TP53_LOH_t == FALSE)   # 0
ABSOLUTE = which(TP53_all$TP53_LOH == TRUE & TP53_all$TP53_LOH_t == FALSE)   # 1
PCN = which(TP53_all$TP53_LOH == FALSE & TP53_all$TP53_LOH_t == TRUE)   # 0

TP53_all$abs_t = NA
TP53_all$abs_t[both] = "1"
TP53_all$abs_t[neither] = "2"
TP53_all$abs_t[ABSOLUTE] = "3"
TP53_all$abs_t[PCN] = "4"


TP53_all$abs_t = factor(TP53_all$abs_t, 
                  labels = c("Both", "Neither", "ABSOLUTE", "PureCN"),
                  levels = c("1", "2", "3", "4"), 
                  ordered = TRUE)

TP53 = table(TP53_all$abs_t)
```

## HLA
Total 143 obs.

##### HLA-A
```{r}
both = which(HLA_all$HLAA_LOH == TRUE & HLA_all$HLAA_LOH_t == TRUE)   # 38
neither = which(HLA_all$HLAA_LOH == FALSE & HLA_all$HLAA_LOH_t == FALSE)   # 95
ABSOLUTE = which(HLA_all$HLAA_LOH == TRUE & HLA_all$HLAA_LOH_t == FALSE)   # 5
PCN = which(HLA_all$HLAA_LOH == FALSE & HLA_all$HLAA_LOH_t == TRUE)   # 5

HLA_all$HLAA_abs_t = NA
HLA_all$HLAA_abs_t[both] = "1"
HLA_all$HLAA_abs_t[neither] = "2"
HLA_all$HLAA_abs_t[ABSOLUTE] = "3"
HLA_all$HLAA_abs_t[PCN] = "4"


HLA_all$HLAA_abs_t = factor(HLA_all$HLAA_abs_t, 
                  labels = c("Both", "Neither", "ABSOLUTE", "PureCN"),
                  levels = c("1", "2", "3", "4"), 
                  ordered = TRUE)

HLAA = table(HLA_all$HLAA_abs_t)
```

##### HLA-B
```{r}
both = which(HLA_all$HLAB_LOH == TRUE & HLA_all$HLAB_LOH_t == TRUE)   # 37
neither = which(HLA_all$HLAB_LOH == FALSE & HLA_all$HLAB_LOH_t == FALSE)   # 100
ABSOLUTE = which(HLA_all$HLAB_LOH == TRUE & HLA_all$HLAB_LOH_t == FALSE)   # 5
PCN = which(HLA_all$HLAB_LOH == FALSE & HLA_all$HLAB_LOH_t == TRUE)   # 1

HLA_all$HLAB_abs_t = NA
HLA_all$HLAB_abs_t[both] = "1"
HLA_all$HLAB_abs_t[neither] = "2"
HLA_all$HLAB_abs_t[ABSOLUTE] = "3"
HLA_all$HLAB_abs_t[PCN] = "4"


HLA_all$HLAB_abs_t = factor(HLA_all$HLAB_abs_t, 
                  labels = c("Both", "Neither", "ABSOLUTE", "PureCN"),
                  levels = c("1", "2", "3", "4"), 
                  ordered = TRUE)

HLAB = table(HLA_all$HLAB_abs_t)
```

##### HLA-C
```{r}
both = which(HLA_all$HLAC_LOH == TRUE & HLA_all$HLAC_LOH_t == TRUE)   # 36
neither = which(HLA_all$HLAC_LOH == FALSE & HLA_all$HLAC_LOH_t == FALSE)   # 98
ABSOLUTE = which(HLA_all$HLAC_LOH == TRUE & HLA_all$HLAC_LOH_t == FALSE)   # 6
PCN = which(HLA_all$HLAC_LOH == FALSE & HLA_all$HLAC_LOH_t == TRUE)   # 3

HLA_all$HLAC_abs_t = NA
HLA_all$HLAC_abs_t[both] = "1"
HLA_all$HLAC_abs_t[neither] = "2"
HLA_all$HLAC_abs_t[ABSOLUTE] = "3"
HLA_all$HLAC_abs_t[PCN] = "4"


HLA_all$HLAC_abs_t = factor(HLA_all$HLAC_abs_t, 
                  labels = c("Both", "Neither", "ABSOLUTE", "PureCN"),
                  levels = c("1", "2", "3", "4"), 
                  ordered = TRUE)

HLAC = table(HLA_all$HLAC_abs_t)
```

##### Summary table
```{r}
summary = rbind(TP53 = TP53, HLAA = HLAA, HLAB = HLAB, HLAC = HLAC)
summary
```

## Summary for stacked bar chart
```{r}
TP53_abs_t_value = round(TP53/sum(TP53)*100, digits = 1)
HLAA_abs_t_value = round(HLAA/sum(HLAA)*100, digits = 1)
HLAB_abs_t_value = round(HLAB/sum(HLAB)*100, digits = 1)
HLAC_abs_t_value = round(HLAC/sum(HLAC)*100, digits = 1)

condition = rep(factor(c("Both", "Neither", "ABSOLUTE", "PureCN"), 
                       levels = c("PureCN", "ABSOLUTE", "Neither", "Both")), 4)

value = c(TP53_abs_t_value, HLAA_abs_t_value, HLAB_abs_t_value, HLAC_abs_t_value)

type = c(rep("TP53", 4), 
         rep("HLA-A", 4),
         rep("HLA-B", 4),
         rep("HLA-C", 4))

data = data.frame(condition, value, type)
```

```{r figure.width=7, figure.height= 5}
LOH_t_plot = ggplot(data, aes(fill=condition, y=value, x = type, order = as.numeric(value))) + 
  geom_bar(stat="identity", position="fill", width = 0.4) +
  labs(title = "E. TCGA-OV: LOH") + 
  theme_light() +
  theme(plot.title = element_text(size = 14, 
                                  face = "bold", 
                                  margin = margin(10, 0, 10, 0)),
        axis.text.x = element_text(size = 10, face = "bold"), 
        axis.text.y = element_text(size = 10, face = "bold"), 
        # axis.title.x = element_text(size = 12, face = "bold"), 
        axis.title.x = element_blank(),
        axis.title.y = element_text(size = 12, face = "bold"),
        # axis.title.y = element_blank(),
        axis.line = element_line(colour = "black", size = 0.5),
        panel.grid.major = element_line(), 
        panel.grid.minor = element_line(),
        legend.position = "none",
        legend.title = element_blank(),
        legend.text = element_text(size = 10, face = "bold"),
        legend.background = element_rect(fill = NA),
        # legend.title = element_text(size = 12, face = "bold"),
        # legend.text = element_text(size = 10, face = "bold"),
        plot.margin = unit(c(0.5,0.5,0.5,0.5), "cm")) +
  scale_y_continuous(labels = scales::percent) + ylab("Concordance") + 
  scale_fill_manual(values = c("grey", "dark grey", "tomato", "red"))

LOH_t_plot
```

```{r eval=FALSE}
saveRDS(LOH_t_plot, file = "~/wallabe4_backup/github/PureCN_manuscript/Figures/Final_Figures/Fig1E.ovc_loh.rds")
```