---
title: "LOH bubble plot"
author: "Sehyun Oh"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
```

```{r, echo=FALSE, results="hide", warning=FALSE, eval=TRUE}
suppressPackageStartupMessages({
    library(magrittr)
    library(GenomicRanges)
    library(ggplot2)
})
```


```{r}
out_dir = "~/data2/PureCN_manuscript/Revision"
loh_list = readRDS(file.path(out_dir, "LOH/data/luad_LOH_all.rds"))
# loh_list = readRDS(file.path(out_dir, "luad_LOH_all_PSCBS.rds"))
names(loh_list) = stringr::str_extract(names(loh_list), "TCGA.{11}")
loh_list = lapply(loh_list, function(x) {x[!is.na(x$C) & !is.na(x$M),]})   # remove NA calls

for (i in seq_along(loh_list)) {
    loh_list[[i]] = loh_list[[i]] %>% 
        dplyr::mutate(major = C-M) %>% 
        tidyr::unite(LOH, "major", "M", sep = "-") %>%
        makeGRangesListFromDataFrame(., keep.extra.columns = TRUE) %>%
        unlist
}
```

```{r}
# concordance ploidy calls (difference in ploidy estimate less than 0.5)
puri_ploi = read.csv("~/data2/PureCN_manuscript/Figures/Final_Tables/Table1_puri_ploi.csv")[,-1]
ploi_diff = abs(puri_ploi$Ploidy_ABS - puri_ploi$Ploidy_PCN_t) < 0.5
puri_ploi = puri_ploi[ploi_diff,]   

# tumor purity greater than 30%
puri_30 = puri_ploi$Purity_PCN_t > 0.3
puri_ploi = puri_ploi[puri_30,]   

# LUAD sampleID for downstream analysis 
luad_sampleId = puri_ploi[which(puri_ploi$Sample == "LUAD"),]$SampleId
loh_list_pcn = loh_list[names(loh_list) %in% luad_sampleId]   # 250 samples from 442
```

`loh_list` is the PureCN GRangesList object with the metadata column `LOH`.
```{r}
loh_list_pcn[1:2]
```


# Load ABSOLUTE GrangesList_hg38
```{r eval=FALSE}
abs_gl = readRDS("~/Documents/github/subtypeHeterogeneity/inst/extdata/ABSOLUTE_grangeslist.rds")
luad_abs_gl = abs_gl[names(abs_gl) %in% luad_sampleId]   # 250 <-- 442 samples

CreateLOHmetadata = function(x) {
    for (i in seq_along(x)) {
        loh = c(x$Modal_HSCN_1[i], x$Modal_HSCN_2[i])
        x$LOH[i] = paste0(max(loh), "-", min(loh))
    }
    return(x)
}

a = CreateLOHmetadata(unlist(luad_abs_gl)) 
b = split(a, as.factor(names(a)))
loh_list_abs = b
```

`loh_list_abs` is the ABSOLUTE GRangesList object with the metadata column `LOH`.
```{r eval=FALSE}
loh_list_abs[1:2]
```

```{r echo=FALSE}
# saveRDS(loh_list_pcn, "~/data2/PureCN_manuscript/Revision/LOH/data/LOH_list_LUAD_purecn.rds")
# saveRDS(loh_list_pcn, "~/data2/PureCN_manuscript/Revision/LOH/data/LOH_list_LUAD_purecn_PSCBS.rds")
# saveRDS(loh_list_abs, "~/data2/PureCN_manuscript/Revision/LOH/data/lOH_list_LUAD_abs.rds")

loh_list_pcn = readRDS("~/data2/PureCN_manuscript/Revision/LOH/data/LOH_list_LUAD_purecn.rds")
loh_list_abs = readRDS("~/data2/PureCN_manuscript/Revision/LOH/data/LOH_list_LUAD_abs.rds")
```

```{r}
loh_summary = list()
for (i in luad_sampleId) {
    
    overlap_ind = findOverlaps(loh_list_pcn[[i]], 
                               loh_list_abs[[i]]) %>% as.data.frame
    
    for (j in seq_along(loh_list_abs[[i]])) {
        queryHits_ind = overlap_ind[which(overlap_ind$subjectHits == j),]$queryHits
        num_repeat = length(queryHits_ind)
        sample_name = luad_sampleId[i]
        loh_summary[[i]] = data.frame(loh.pcn = loh_list_pcn[[i]]$LOH[queryHits_ind],
                                      loh.abs = rep(loh_list_abs[[i]]$LOH[j], num_repeat))
    }
}
```

```{r echo=FALSE, eval=TRUE}
# saveRDS(loh_summary, "~/data2/PureCN_manuscript/Revision/LOH/data/LUAD_LOH_summary.rds")

loh_summary = readRDS("~/data2/PureCN_manuscript/Revision/LOH/data/LUAD_LOH_summary.rds")
```

```{r eval=TRUE}
test = data.frame()
for (i in seq_along(loh_summary)) {test = rbind(test, loh_summary[[i]])}

unique_abs = unique(test$loh.abs) %>% as.character() %>% sort
unique_pcn = unique(test$loh.pcn) %>% as.character() %>% sort
```

```{r eval=TRUE}
t = as.data.frame(matrix(NA,
                         nrow=length(unique_abs),
                         ncol=length(unique_pcn)))
rownames(t) = unique_abs
colnames(t) = unique_pcn
for (i in unique_abs) {
    for (j in unique_pcn) {
        t[i,j] = sum(test$loh.abs == i & test$loh.pcn == j)
    }
}
```

```{r eval=TRUE}
t2 = as.data.frame(matrix(NA,
                         nrow=length(unique_abs)*length(unique_pcn),
                         ncol=3))
colnames(t2) = c("loh.abs", "loh.pcn", "num")
t2$loh.abs = rep(unique_abs, each = length(unique_pcn))
t2$loh.pcn = rep(unique_pcn, length(unique_abs))

for (i in unique_abs) {
    for (j in unique_pcn) {
        ind = which(t2$loh.abs == i & t2$loh.pcn == j)
        t2$num[ind] = t[i,j]
    }
}

# subset the table only with the LOH combination detected in ABSOLUTE
t2 = t2[which(t2$loh.pcn %in% unique_abs),]
```

```{r eval=TRUE}
# figure styling
source("~/data2/PureCN_manuscript/Figures/manuscript_figure_style.R")

luad_loh_all = ggplot(t2, aes(x = loh.abs, y = loh.pcn)) +   # 30,335 data points
    geom_point(aes(size = num), alpha = 0.5, show.legend = FALSE) +
    geom_text(aes(label = num), col = "white", size = 3) +
    # scale_color_manual(values = c("#00AFBB", "#E7B800", "#FC4E07")) +
    scale_size(range = c(0.5, 25)) +
    ggtitle("F. TCGA-LUAD: Integer Copy Number") +
    xlab("SNP6 array (ABSOLUTE)") + ylab("Tumor WES (PureCN)") +
    customPlot
```

```{r fig.width=5, fig.height=5, eval=TRUE}
luad_loh_all

out_dir = "~/data2/PureCN_manuscript/Figures/Final_Figures"
saveRDS(luad_loh_all, file = file.path(out_dir, "Fig1F.luad_loh_all.rds"))
```

```{r eval=TRUE, echo=FALSE}
loh_summary = readRDS("~/data2/PureCN_manuscript/Revision/LOH/data/LUAD_LOH_summary.rds")
discordant = sapply(loh_summary, function(x) {sum(x$loh.pcn == "2-1" & x$loh.abs == "2-2")})
discordant_sampleId = names(which(discordant != 0))
loh_summary[discordant_sampleId] = NULL

test = data.frame()
for (i in seq_along(loh_summary)) {test = rbind(test, loh_summary[[i]])}
unique_abs = unique(test$loh.abs) %>% as.character() %>% sort
unique_pcn = unique(test$loh.pcn) %>% as.character() %>% sort

t = as.data.frame(matrix(NA,
                         nrow=length(unique_abs),
                         ncol=length(unique_pcn)))
rownames(t) = unique_abs
colnames(t) = unique_pcn
for (i in unique_abs) {
    for (j in unique_pcn) {
        t[i,j] = sum(test$loh.abs == i & test$loh.pcn == j)
    }
}

t2 = as.data.frame(matrix(NA,
                         nrow=length(unique_abs)*length(unique_pcn),
                         ncol=3))
colnames(t2) = c("loh.abs", "loh.pcn", "num")
t2$loh.abs = rep(unique_abs, each = length(unique_pcn))
t2$loh.pcn = rep(unique_pcn, length(unique_abs))

for (i in unique_abs) {
    for (j in unique_pcn) {
        ind = which(t2$loh.abs == i & t2$loh.pcn == j)
        t2$num[ind] = t[i,j]
    }
}

# subset the table only with the LOH combination detected in ABSOLUTE
t2 = t2[which(t2$loh.pcn %in% unique_abs),]

# figure styling
source("~/data2/PureCN_manuscript/Figures/manuscript_figure_style.R")

luad_loh_all = ggplot(t2, aes(x = loh.abs, y = loh.pcn)) +   # 30,335 data points
    geom_point(aes(size = num), alpha = 0.5, show.legend = FALSE) +
    geom_text(aes(label = num), col = "white", size = 3) +
    # scale_color_manual(values = c("#00AFBB", "#E7B800", "#FC4E07")) +
    scale_size(range = c(0.5, 25)) +
    ggtitle("F. TCGA-LUAD: Integer Copy Number") +
    xlab("SNP6 array (ABSOLUTE)") + ylab("Tumor WES (PureCN)") +
    customPlot
```

```{r fig.width=5, fig.height=5, eval=TRUE}
luad_loh_all

out_dir = "~/data2/PureCN_manuscript/Figures/Final_Figures"
saveRDS(luad_loh_all, file = file.path(out_dir, "Fig1F.luad_loh_all_v2.rds"))
```


