---
title: "LOH bubble plot for FACETS"
author: "Sehyun Oh"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval=FALSE)
```

```{r, echo=FALSE, results="hide", warning=FALSE, eval=TRUE}
suppressPackageStartupMessages({
    library(magrittr)
    library(GenomicRanges)
    library(ggplot2)
})
```

```{r eval=TRUE}
out_dir = "~/Documents/github/FACETS/LUAD/facets"
facets_files = list.files(out_dir)
facets_files = file.path(out_dir, facets_files)
```

```{r}
res = list()
for (i in seq_along(facets_files)) {
    x = facets_files[i]
    output = readRDS(x)$cncf
    output = output[c("chrom", "start", "end", "tcn.em", "lcn.em")]
    names(output) = c("chr", "start", "end", "tcn.em", "lcn.em")
    
    output$chr = paste0("chr", output$chr)
    output = output[!is.na(output$tcn.em) & !is.na(output$lcn.em),]   # remove any NA call
    sampleId = stringr::str_extract(x, "TCGA.{11}")
    res[[sampleId]] = output
}
```

Subset the same samples used for PureCN
```{r}
# concordance ploidy calls (difference in ploidy estimate less than 0.5)
puri_ploi = read.csv("~/data2/PureCN_manuscript/Figures/Final_Tables/Table1_puri_ploi.csv")[,-1]
ploi_diff = abs(puri_ploi$Ploidy_ABS - puri_ploi$Ploidy_PCN_t) < 0.5
puri_ploi = puri_ploi[ploi_diff,]   

# tumor purity greater than 30%
puri_30 = puri_ploi$Purity_PCN_t > 0.3
puri_ploi = puri_ploi[puri_30,]   

# LUAD sampleID for downstream analysis 
luad_sampleId = puri_ploi[which(puri_ploi$Sample == "LUAD"),]$SampleId

res = res[which(names(res) %in% luad_sampleId)]
```

`loh_list_facets` is the FACETS GRangesList object with the metadata column `LOH`.
```{r}
loh_list_facets = res
for (i in seq_along(loh_list_facets)) {
    loh_list_facets[[i]]$major = loh_list_facets[[i]]$tcn.em - loh_list_facets[[i]]$lcn.em
    loh_list_facets[[i]] = loh_list_facets[[i]] %>% 
        tidyr::unite(LOH, "major", "lcn.em", sep = "-") %>%
        makeGRangesListFromDataFrame(., keep.extra.columns = TRUE) %>%
        unlist
}
```

```{r}
loh_list_facets[1:2]
```



# Load ABSOLUTE GrangesList_hg38
```{r}
abs_gl = readRDS("~/Documents/github/subtypeHeterogeneity/inst/extdata/ABSOLUTE_grangeslist.rds")
luad_abs_gl = abs_gl[names(abs_gl) %in% luad_sampleId]   # 250 <-- 442 samples

CreateLOHmetadata = function(x) {
    for (i in seq_along(x)) {
        loh = c(x$Modal_HSCN_1[i], x$Modal_HSCN_2[i])
        x$LOH[i] = paste0(max(loh), "-", min(loh))
    }
    return(x)
}

a = CreateLOHmetadata(unlist(luad_abs_gl)) 
b = split(a, as.factor(names(a)))
loh_list_abs = b
```

`loh_list_abs` is the ABSOLUTE GRangesList object with the metadata column `LOH`.
```{r}
loh_list_abs[1:2]
```

```{r eval=FALSE, echo=FALSE}
saveRDS(loh_list_facets, "~/data2/PureCN_manuscript/Revision/LOH/loh_list_facets.rds")
```

```{r}
loh_summary = list()
for (i in luad_sampleId) {
    
    overlap_ind = findOverlaps(loh_list_facets[[i]], 
                               loh_list_abs[[i]]) %>% as.data.frame
    
    for (j in seq_along(loh_list_abs[[i]])) {
        queryHits_ind = overlap_ind[which(overlap_ind$subjectHits == j),]$queryHits
        num_repeat = length(queryHits_ind)
        sample_name = luad_sampleId[i]
        loh_summary[[i]] = data.frame(loh.facets = loh_list_facets[[i]]$LOH[queryHits_ind],
                                      loh.abs = rep(loh_list_abs[[i]]$LOH[j], num_repeat))
    }
}
```

```{r echo=FALSE, eval=TRUE}
# saveRDS(loh_summary, "~/data2/PureCN_manuscript/Revision/LOH/loh_summary_facets.rds")
loh_summary = readRDS("~/data2/PureCN_manuscript/Revision/LOH/loh_summary_facets.rds")
```





```{r eval=TRUE}
test = data.frame()
for (i in seq_along(loh_summary)) {test = rbind(test, loh_summary[[i]])}

unique_abs = unique(test$loh.abs) %>% as.character() %>% sort
unique_facets = unique(test$loh.facets) %>% as.character() %>% sort
```

```{r eval=TRUE}
t = as.data.frame(matrix(NA,
                         nrow=length(unique_abs),
                         ncol=length(unique_facets)))
rownames(t) = unique_abs
colnames(t) = unique_facets
for (i in unique_abs) {
    for (j in unique_facets) {
        t[i,j] = sum(test$loh.abs == i & test$loh.facets == j)
    }
}
```

```{r eval=TRUE}
t2 = as.data.frame(matrix(NA,
                         nrow=length(unique_abs)*length(unique_facets),
                         ncol=3))
colnames(t2) = c("loh.abs", "loh.facets", "num")
t2$loh.abs = rep(unique_abs, each = length(unique_facets))
t2$loh.facets = rep(unique_facets, length(unique_abs))

for (i in unique_abs) {
    for (j in unique_facets) {
        ind = which(t2$loh.abs == i & t2$loh.facets == j)
        t2$num[ind] = t[i,j]
    }
}

# subset the table only with the LOH combination detected in ABSOLUTE
t2_facets = t2[which(t2$loh.facets %in% unique_abs),]
```

```{r eval=TRUE, fig.width=5, fig.height=5}
ggplot(t2_facets, aes(x = loh.abs, y = loh.facets)) +    # 231 data points
    geom_point(aes(size = num), alpha = 0.5, show.legend = FALSE) +
    geom_text(aes(label = num), col = "white", size = 3) +
    # scale_color_manual(values = c("#00AFBB", "#E7B800", "#FC4E07")) +
    scale_size(range = c(0.5, 25)) +
    ggtitle("D. TCGA-LUAD: LOH (from FACETS)") +
    xlab("SNP6 array (ABSOLUTE)") + ylab("Tumor/Normal (FACETS)")
```



